[project]
name = "bci-lab"
version = "0.1.0"
description = "BCI / EEG research with MOABB and MNE"
requires-python = ">=3.10,<3.12"

dependencies = [
  "jupyterlab",
  "ipykernel",
  "numpy",
  "scipy",
  "pandas",
  "matplotlib",
  "mne",
  "moabb==1.4.3",
  "scikit-learn>=1.6"
]
